<?php

return [
    'skills' => [
        'PHP',
        'Laravel',
        'Livewire',
        'Symfony',
        'Node.js',
        'NestJS',
        'React',
        'Vue.js',
        'Angular',
        'Next.js',
        'Tailwind CSS',
        'MySQL',
        'PostgreSQL',
        'MariaDB',
        'MongoDB',
        'Redis',
        'Flutter',
        'React Native',
        'Swift',
        'Kotlin',
        'Docker',
        'AWS',
        'Cloudflare',
        'Nginx',
        'DevOps',
        'Figma',
        'UX',
        'UI',
        'Prototipado IA',
        'Diseño grafico',
        'UI saas',
    
    ],
    'skins' => [
        'Frontend',
        'Backend',
        'Full Stack',
        'Mobile',
        'DevOps',
        'QA',
        'Data',
        'AI'
    ],
];
